all: corpus helloworld

corpus:
	rezc test1.txt
	rezc test2.txt
	rezc test3.txt
	rezc test4.txt
	rezc test5.txt
	rezc test6.txt
	rezc test7.txt

helloworld:
	rezc helloworld.txt

clean:
	rm -rf *.bin